version: '3.8'

services:


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "yosra"
      MYSQL_PASSWORD: "AZERTY123456@"
      MYSQL_ROOT_PASSWORD: "AZERTY123456@"  # Must match application.properties
    ports:
      - "3307:3306"
 
    volumes:
      - mysql_data:/var/lib/mysql
 

  tp-foyer:
    image: yosra/tp-foyer:1.0.0  # Your Docker image name and tag
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "yosra"
      SPRING_DATASOURCE_PASSWORD: "AZERTY123456@"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: "/tpfoyer"
    ports:
      - "8089:8089"

    depends_on:
      - mysql

    restart: always

  angular-app:
    image: shilyosra/angular-app:1.0.0
    ports:
      - "81:81"
    depends_on:
      - tp-foyer

volumes:
  mysql_data:
  grafana_data:

