global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds

scrape_configs:
  - job_name: 'tp-foyer'
    metrics_path: '/tpfoyer/actuator/prometheus'  # This should be the path where metrics are exposed in tp-foyer
    static_configs:
      - targets: ['tp-foyer:8089']  # Target tp-foyer on port 8089

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
